CFLAGS = -g -Wall

all: 1 2 3 4 5 6 7 8

1: 1.c include/binary_linked_list.c
	gcc $(CFLAGS) $^ -o 1.out

2: 2.c include/binary_linked_list.c
	gcc $(CFLAGS) $^ -o 2.out

3: 3.c include/binary_linked_list.c
	gcc $(CFLAGS) $^ -o 3.out

4: 4.c include/binary_linked_list.c
	gcc $(CFLAGS) $^ -o 4.out

5: 5.c include/binary_linked_list.c
	gcc $(CFLAGS) $^ -o 5.out

6: 6.c include/binary_linked_list.c
	gcc $(CFLAGS) $^ -o 6.out

7: 7.c include/binary_linked_list.c
	gcc $(CFLAGS) $^ -o 7.out

8: 8.c include/binary_linked_list.c
	gcc $(CFLAGS) $^ -o 8.out

.PHONY: clean
clean: 
	rm *.out 
