all: 1 2 3 4 5 6 7 8 9 10

1: 1.c linked_list.c
	gcc -g -o 1.out 1.c linked_list.c

2: 2.c linked_list.c
	gcc -g -o 2.out 2.c linked_list.c

3: 3.c linked_list.c
	gcc -g -o 3.out 3.c linked_list.c

4: 4.c linked_list.c
	gcc -g -o 4.out 4.c linked_list.c

5: 5.c linked_list.c
	gcc -g -o 5.out 5.c linked_list.c

6: 6.c linked_list.c
	gcc -g -o 6.out 6.c linked_list.c

7: 7.c linked_list.c
	gcc -g -o 7.out 7.c linked_list.c

8: 8.c linked_list.c
	gcc -g -o 8.out 8.c linked_list.c

9: 9.c linked_list.c
	gcc -g -o 9.out 9.c

10: 10.c linked_list.c
	gcc -g -o 10.out 10.c seq_list.c

.PHONY: clean
clean:
	rm *.out
